### ISSUE TITLE
Cache-control: can't get a 304 response from cached files, always returns 200

### ISSUE THREAD

**Issue by alfonso100** [SatelliteWP/rocket-nginx#153]
Hey Maxime, I am Alfonso from WP Rocket's support team. 
First of all: THANK YOU for your work on this NGINX config file. It is awesome and we continuously recommend it to our customers. 

This is more a question than a bug request.
I can see that the configuration file sets the following **cache-control** headers for HTML docs:

`Cache-Control: no-cache, no-store, must-revalidate`

Is it correct to say that with these headers, the server response will be always 200? 
There will be no 304 in any case because the cache-control is instructing the browser to not cache, not store any HTML. 

And, in order to achieve a 304 response, the cache-control header should be modified to __Public, max-age=0_ ?
In which case, the website should be carefully tested because of this issue:
https://github.com/SatelliteWP/rocket-nginx/issues/43#issuecomment-282252325

I would like to confirm if this is the expected behavior so we can update our docs. 
thank you!!

**Comment by maximejobin** [comment]
Hey Alfonso!

Thank you for your kind words!

The goal of this configuration is to be as generic as possible. Note that it is possible to change the default behavior in the configuration file (ini file):
https://github.com/SatelliteWP/rocket-nginx/blob/master/rocket-nginx.ini.disabled#L21

If you want to know why I did not set the `Cache-Control` to `public`, you can see this doc from Mozilla:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#cacheability

Caching is complex and I wanted every change made in the HTML to be sent to the browser automatically without having to wait.

To answer your question, if you want to get a 304, you'll need to add a `If-Modified-Since` header as per RFC 2616:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25

If you still have questions, please let me know!

**Comment by alfonso100** [comment]
Hi Maxime! thank you for your answer. 
It makes sense. I will update our docs with a small note about this, I think our NGINX users will find it useful.

Have a great day and keep up the good work! 🙏
