### ISSUE TITLE
Facing SET directive issue while testing Nginx File 

### ISSUE THREAD

**Issue by pantdeepakk5** [SatelliteWP/rocket-nginx#172]
Hi Team 

I performed the exact steps you described here but on testing the config file I am facing below issue.

`nginx: [emerg] "set" directive is not allowed here in /etc/nginx/rocket-nginx/conf.d/defau lt.conf:19`

Any help would be really appreciated. 

Thanks

**Comment by maximejobin** [comment]
You probably did not include the file correctly and the right place.

1) Can you show your site's configuration?

2) Are you using Plesk? If so, many people have had problems configuring Rocket-Nginx because they do not understand how Plesk does its configuration. The problem is not with Rocket-Nginx per se but how and where to do it. Unfortunately, I do not have a Plesk environment so I cannot help.
