### ISSUE TITLE
Cache MISS after upgrading wp-rocket to 3.17.0.1

### ISSUE THREAD

**Issue by guichhh** [SatelliteWP/rocket-nginx#221]
**Describe the bug**
After upgrading WP Rocket from 3.16.4 to 3.17.0.1 the cache is no longer populating at cache/wp-rocket/ so seeing MISS in header due to File not cached. On 3.16.4 we had it working correctly and I haven't altered rocket-nginx configuration at all, I only upgraded the wp-rocket plugin files.

Can you tell me what is the most recent version of wp-rocket that rocket-nginx is compatible with? Are wp-rocket and rocket-nginx version numbers synchronised for this purpose? I can rollback if need be.

**Versions**
What version of Nginx are you using ? nginx/1.26.1
What version of Rocket-Nginx are you using ? 3.10
What version of WP Rocket are you using ? 3.17.0.1
Are you using Nginx as a reverse proxy (with Apache for instance) ? No

Thanks in advance

**Comment by maximejobin** [comment]
Rocket-Nginx is serving files generated by WP-Rocket. The only thing the configuration does is serving your cached files faster.

If the cache files are not generated, that is why you see a MISS status. The problem comes from WP Rocket.

I would like to investigate but I do not have access to the 3.17 version as the deployment is made by batch. That being said, I doubt it has anything to do with Rocket-Nginx. You can try disable it and validate.
